name: vulnerability-scan
on:
  - push
  - workflow_dispatch

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    env:
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get short SHA
        run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: vulnerable-container:${{ env.GHA_SHA }}
          load: true

      - name: lw-scanner
        uses: timarenz/lw-scanner-action@v0.3.1
        env:
          LW_SCANNER_SAVE_RESULTS: true
          LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
        with:
          image_name: vulnerable-container
          image_tag: ${{ env.GHA_SHA }}
          fail_if_critical_vulnerabilities_found: false
          fail_if_high_vulnerabilities_found: false
          fail_if_medium_vulnerabilities_found: false
